version: '1.0.0' 
 
dls_settings: 
  log_filepath: '/tmp/duologsync.log' 
  log_format: 'JSON' 
  api: 
    offset: 30 
    timeout: 120 
 
servers: 
  - id: 'USM_Anywhere' 
    hostname: '1.5.3.7' # Use your USM Sensor IP address
    port: 601 
    protocol: TCP 
 
account: 
  ikey: 'AAAAAAAAAAAAAAAAAAA' # From Duo
  skey: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # From Duo
  hostname: 'api-b33f9999.duosecurity.com' # From Duo
  endpoint_server_mappings: 
    - endpoints: ['adminaction', 'auth', 'telephony'] 
      server: 'USM_Anywhere' 
  is_msp: False # DO NOT change this value unless instructed
